---
title: 'W203 Lab 1: Candidate Debt EDA'
author: "Yulia and Mitch"
date: \today
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
# correcting variable names
var_names <- colnames(read.csv("CandidateDebt.csv", nrows = 1))

var_names_corrected <- c(var_names[1:grep("position", var_names)],
                         "position2",
                         var_names[(grep("position", var_names) + 1):(length(var_names) - 1)])
```


```{r}
# reading the data with correct headers
CandidateDebt <- read.csv("CandidateDebt.csv", 
                          stringsAsFactors = FALSE,
                          col.names = var_names_corrected)
```

```{r}
str(CandidateDebt)
```

```{r}
# remove records with missing record type (missing values are miscoded as #NA)
CandidateDebt <- CandidateDebt[!grepl('#N/A', CandidateDebt$recordtype),]
```

```{r}
# converting amount from character to numeric
CandidateDebt$amount <- as.numeric(CandidateDebt$amount)
```

```{r}
summary(CandidateDebt$amount)
```


```{r}
# converting dates from character to dates
CandidateDebt$fromdate <- as.Date(CandidateDebt$fromdate, format = "%m/%d/%Y")
CandidateDebt$thrudate <- as.Date(CandidateDebt$thrudate, format = "%m/%d/%Y")
CandidateDebt$debtdate <- as.Date(CandidateDebt$debtdate, format = "%m/%d/%Y")
```

```{r}
# creating a vector of variables to keep for analysis
keep_vars <- c("reportnumber", "filerid", "filername", "office", "legislativedistrict",
    "party", "jurisdiction", "jurisdictioncounty", "jurisdictiontype",
    "amount", "fromdate", "thrudate", "debtdate", "code", "description",
    "vendorname", "vendorcity", "vendorstate")

CandidateDebt <- CandidateDebt[keep_vars]
```

```{r}
str(CandidateDebt)
```

```{r}
summary(CandidateDebt)
```

```{r}
# checking if there are any "#NA" values left
sapply(CandidateDebt, function(x) sum(grepl('#NA', x)))
```

```{r}
# checking for presense of missing values
sum(is.na(CandidateDebt))
```

```{r}
# checking some variables with smaller number of unique values
cat_vars <- c("office", "legislativedistrict", "party", "jurisdiction", "jurisdictioncounty",
              "jurisdictiontype", "fromdate", "thrudate", "debtdate", "code",  
              "vendorcity", "vendorstate")
sapply(CandidateDebt[, cat_vars], function(x) table(x))
```

```{r}
save(CandidateDebt, file = "CandidateDebt.RData")
```

